language: php

before_script:
 - sudo apt-get install python-software-properties -y # for the next command 
 - sudo add-apt-repository ppa:eyecreate/haxe -y      # add the ubuntu ppa that contains haxe
 - sudo apt-get update                                # pull info from ppa
 - sudo apt-get install haxe -y                       # install haxe (and neko)
 - sudo apt-get install gcc-multilib g++-multilib -y  # VM is 64bit but hxcpp builds 32bit
 - mkdir ~/haxelib                                    # create a folder for installing haxelib
 - haxelib setup ~/haxelib
 - haxelib install hxcpp                              # install hxcpp to test C++ target
 - mkdir bin                                          # create an output folder if needed

script:
 - haxe build.hxml